# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jaime Alberto Hernandez Robles
title: ING. EN COMPUTACION
email: Your email (optional)
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  jekyll
stackoverflow_username: "00000001"
#dribbble_username: jekyll
facebook_username: jekyll
#flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Me considero una persona adaptable, siempre dispuesta a aprender nuevas tecnologías y mejorar mis habilidades para enfrentar nuevos retos.
  Disfruto trabajar en equipos multidisciplinarios, donde puedo colaborar con otros para alcanzar objetivos comunes y aprender de diferentes perspectivas


  Lenguages de Programacion...
    - Python
    - C
    - C++
    - C#
    - Java
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Vital Sings Vision 
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: (INDAUTOR 03-2024-092709223000-01)
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Me encargué del diseño de la redes neuronales para el reconocimiento de los patrones de un latido cardiaco y la detección de un paro cardíaco, además del desarrollo del sistema de endpoints y de las comunicaciones entre los servidores e interfaces de usuarios.
        description: | # this will include new lines to allow paragraphs
          Un software especializado para la detección temprana de paros cardíacos, utilizando algoritmos de 
          análisis de señales biomédicas y técnicas de machine learning para identificar patrones anormales 
          en tiempo real
    
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: administrador de Secundarias 
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Diseñe un software personalizado para la gestión administrativa del personal, mejorando la eficiencia operativa en un 60%
        description: | # this will include new lines to allow paragraphs
          Un software a medida para la gestión administrativa del personal, diseñado para optimizar y automatizar procesos clave en la administración de recursos humanos. Esta solución ha logrado mejorar la eficiencia operativa en un 60%, facilitando la organización de datos, el control de asistencia, la gestión de permisos y la generación de reportes en tiempo real.
          Este software no solo ha agilizado los procesos de administración de personal, sino que ha permitido a los gestores tomar decisiones informadas, reduciendo los tiempos operativos y aumentando la productividad en general.

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Webcrawler con Reconocimiento Facial
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Supervise el desarrollo del proyecto y aporte sugerencias sobre las tecnologías y lenguajes a usar, mas aparte diseñe el código para reconocimiento facial 
        description: | # this will include new lines to allow paragraphs
          Este proyecto consiste en un webcrawler desarrollado en Python, diseñado para realizar búsquedas de personas en Internet mediante la comparación de imágenes. Al ingresar el nombre de una persona, el webcrawler utiliza Google para localizar imágenes asociadas a ese nombre y luego las compara con una imagen de referencia proporcionada. Las coincidencias encontradas se separan de las imágenes no relacionadas, permitiendo una búsqueda más precisa y eficiente.
          Este sistema puede utilizarse en diversas aplicaciones, desde la búsqueda de información sobre una persona específica en redes sociales hasta la automatización de análisis de imágenes para investigaciones. Su arquitectura modular permite adaptaciones para mejorar la precisión y añadir funcionalidades adicionales, como análisis de metadatos o filtros de contenido.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Monitoreo de Abejas
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Lidere el desarrollo del proyecto y diseñe los algoritmos de cómputo regresivo 
        description: | # this will include new lines to allow paragraphs
          Este proyecto consiste en un panel de control inteligente, desarrollado con Flask y C++, diseñado para proteger a las abejas utilizadas en la polinización dentro de invernaderos. El sistema monitorea y predice la temperatura y humedad del ambiente controlado, previniendo cambios drásticos que podrían poner en riesgo la vida de las abejas debido a condiciones extremas.
          Este sistema es una herramienta crucial para apicultores que dependen de abejas para la polinización en ambientes controlados. Con su capacidad predictiva y monitoreo constante, ayuda a mantener condiciones seguras para las abejas, optimizando la productividad y reduciendo el riesgo de mortalidad por condiciones ambientales desfavorables.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Secretaría de Educación Pública
        sub_title: Desarrollador de software
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          La Secretaría de Educación Pública (SEP) es una de las diecinueve secretarías de Estado que, junto con la Consejería Jurídica del Ejecutivo Federal, conforman el gabinete legal del presidente de México.
          Es la encargada de diseñar, ejecutar y coordinar las políticas públicas en materia de Educación.
        description: | # this will include new lines to allow paragraphs
          Desarrollé y lideré la creación de un software personalizado para la gestión administrativa del personal, mejorando la eficiencia operativa en un 60%
          Tengo experiencia laboral en el diseño y desarrollo de soluciones de software administrativo, orientadas a optimizar y automatizar procesos internos en entornos empresariales. He trabajado en la creación de herramientas que facilitan la gestión de datos, el control de inventarios, la generación de informes financieros y el seguimiento de procesos operativos, mejorando la eficiencia y reduciendo el tiempo de ejecución de tareas administrativas.
          Esta experiencia me ha permitido desarrollar un enfoque orientado a las necesidades del usuario, garantizando soluciones personalizadas que mejoran la productividad y la organización en las operaciones diarias empresariales.
          
      - layout: right
        title: Secretaría de Educación Pública
        sub_title: administrativo
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          La Secretaría de Educación Pública (SEP) es una de las diecinueve secretarías de Estado que, junto con la Consejería Jurídica del Ejecutivo Federal, conforman el gabinete legal del presidente de México.
          Es la encargada de diseñar, ejecutar y coordinar las políticas públicas en materia de Educación.
        description: | # this will include new lines to allow paragraphs
          Gestioné de manera eficiente la administración de archivos y datos, asegurando la correcta organización, almacenamiento y recuperación de información en sistemas tanto locales como en la nube.
          Implementé políticas de seguridad y respaldo de datos, garantizando la protección y disponibilidad de la información crítica de la empresa.
          Realicé el mantenimiento preventivo y correctivo de equipos computacionales, incluyendo la reparación de hardware, instalación de software y configuración de redes internas.
          Diagnostiqué y resolví problemas técnicos, minimizando el tiempo de inactividad de los sistemas y mejorando la productividad del equipo.
          
      - layout: right
        title: Secretaría de Educación Pública
        sub_title: Profesor
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          La Secretaría de Educación Pública (SEP) es una de las diecinueve secretarías de Estado que, junto con la Consejería Jurídica del Ejecutivo Federal, conforman el gabinete legal del presidente de México.
          Es la encargada de diseñar, ejecutar y coordinar las políticas públicas en materia de Educación.
        description: | # this will include new lines to allow paragraphs
          He trabajado como profesor de computación, tecnologías y matemáticas básicas en la Secretaría de Educación Pública, impartiendo clases a distintos niveles educativos. Mi enfoque se centra en hacer accesibles y comprensibles temas clave en tecnología y matemáticas, fomentando en los estudiantes habilidades prácticas y pensamiento lógico para que puedan aplicarlos en su vida diaria y futura.
          Esta experiencia docente me ha permitido desarrollar habilidades de comunicación efectiva y métodos de enseñanza adaptativos, logrando que los estudiantes adquieran habilidades esenciales en áreas fundamentales del conocimiento.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Universidad de Guadalajara
        sub_title: (COMPUTACION)
        caption: (2020 - present)
        quote: >
          La Ingeniería en Computación es una disciplina que combina conocimientos de ingeniería y ciencias de la computación para diseñar, desarrollar e implementar sistemas y soluciones tecnológicas avanzadas. Esta carrera forma profesionales capaces de trabajar en diversas áreas, desde el desarrollo de software y la arquitectura de hardware hasta la inteligencia artificial y la gestión de redes y sistemas.
        description: | # this will include new lines to allow paragraphs
          Puedo desempeñarme en el desarrollo de software, administración de bases de datos, análisis de datos, inteligencia artificial, ciberseguridad, redes y telecomunicaciones, investigación, y más. Son profesionales esenciales en empresas de tecnología, instituciones financieras, organismos de gobierno, y centros de investigación, entre otros sectores.
          Esta carrera no solo impulsa la innovación tecnológica, sino que también permite la creación de herramientas y soluciones que impactan directamente en la sociedad. Los ingenieros en computación juegan un papel crucial en la transformación digital, contribuyendo al desarrollo de tecnologías que mejoran la eficiencia, seguridad y accesibilidad de servicios.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      HABILIDADES...
        - Liderazgo
        - Comunicación asertiva
        - Gestión de activos
        - Resolución de problemas
        - Elaboración de reportes
        - Trabajo en equipo

      Habilidades Técnicas (Computación y Desarrollo)...
        - Programación en Python y C++: Dominio en la creación de soluciones de software en estos lenguajes.
        - Desarrollo Web con Flask: Creación de aplicaciones web y paneles de control interactivos.
        - Reconocimiento Facial: Implementación de algoritmos para reconocimiento facial y procesamiento de imágenes.
        - Web Scraping: Experiencia en recolección de datos web mediante herramientas como BeautifulSoup y Selenium.
        - Bases de Datos: Diseño y administración de bases de datos SQL para la gestión de datos empresariales.
        - Algoritmos de Machine Learning y Regresión: Aplicación de algoritmos para predicciones en datos de temperatura y humedad.
        - Automatización de Procesos: Creación de scripts y herramientas para automatizar tareas administrativas.
        - Control de Versiones con Git: Manejo de código fuente y colaboración en proyectos a través de Git.

      Habilidades en Desarrollo de Software Administrativo...
        - Gestión de Recursos Humanos: Desarrollo de software para optimizar la administración de personal, incluyendo control de asistencia y permisos.
        - Generación de Reportes Dinámicos: Creación de reportes detallados y gráficos interactivos para análisis en tiempo real.
        - Interfaces de Usuario (UI): Diseño de interfaces intuitivas para mejorar la experiencia del usuario.
        - Optimización de Eficiencia Operativa: Implementación de soluciones de software que mejoran la eficiencia en hasta un 60%.
        - Adaptación y Escalabilidad de Software: Creación de sistemas personalizados y escalables según las necesidades de cada organización.

      Habilidades de Enseñanza y Comunicación...
        - Docencia en Computación y Matemáticas Básicas: Experiencia en la enseñanza de informática y matemáticas en el sector educativo público.
        - Alfabetización Digital: Capacitación en el uso de herramientas tecnológicas para estudiantes de diversos niveles.
        - Desarrollo de Pensamiento Lógico y Resolución de Problemas: Fomento de habilidades lógicas y analíticas en estudiantes.
        - Adaptación de Contenidos Educativos: Creación de material didáctico que se adapta a distintos niveles de aprendizaje.
        - Comunicación Efectiva y Pedagogía: Habilidades en la transmisión de conocimientos técnicos a través de métodos claros y accesibles.

    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
